python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert ISR_ttZ-ISR_WZ-ISR_ZZ
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert ISR_tZq-ISR_tWZ-ISR_ttX
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert ISR_triBoson-ISR_ggToZZ-FSR
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert muR_ttZ-muR_WZ-muR_ZZ
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert muF_ttZ-muF_WZ-muF_ZZ
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert muR_tZq-muR_tWZ-muR_ttX
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert muR_triBoson-muF_tZq-muF_tWZ
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert muF_ttX-muF_triBoson-WZ_Njet_reweight
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert WZ_heavyFlavour-EWK_mul_WZ-EWK_mul_ZZ
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert EWK_add_WZ-EWK_add_ZZ-rate_ttZ
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert rate_WZ-rate_ZZ-rate_ttX
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert rate_triBoson-rate_tWZ-rate_tZq
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert rate_ggToZZ-eft_tWZ-eft_tZq
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Fakerate_muon_2016preVFP-Fakerate_muon_2016-Fakerate_muon_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Fakerate_muon_2018-Fakerate_elec_2016preVFP-Fakerate_elec_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Fakerate_elec_2017-Fakerate_elec_2018-FakerateClosure_correlated_elec
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert FakerateClosure_uncorrelated_elec_2016preVFP-FakerateClosure_uncorrelated_elec_2016-FakerateClosure_uncorrelated_elec_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert FakerateClosure_uncorrelated_elec_2018-FakerateClosure_correlated_muon-FakerateClosure_uncorrelated_muon_2016preVFP
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert FakerateClosure_uncorrelated_muon_2016-FakerateClosure_uncorrelated_muon_2017-FakerateClosure_uncorrelated_muon_2018
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert FakerateClosure_correlated_both-FakerateClosure_uncorrelated_both_2016preVFP-FakerateClosure_uncorrelated_both_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert FakerateClosure_uncorrelated_both_2017-FakerateClosure_uncorrelated_both_2018-Lumi_uncorrelated_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Lumi_uncorrelated_2017-Lumi_uncorrelated_2018-Lumi_correlated_161718
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Lumi_correlated_1718-BTag_b_correlated-BTag_l_correlated
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert BTag_b_uncorrelated_2016preVFP-BTag_l_uncorrelated_2016preVFP-BTag_b_uncorrelated_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert BTag_l_uncorrelated_2016-BTag_b_uncorrelated_2017-BTag_l_uncorrelated_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert BTag_b_uncorrelated_2018-BTag_l_uncorrelated_2018-LepReco
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert LepIDsys_muon-LepIDstat_muon_2016preVFP-LepIDstat_muon_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert LepIDstat_muon_2017-LepIDstat_muon_2018-LepIDsys_elec
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert LepIDstat_elec_2016preVFP-LepIDstat_elec_2016-LepIDstat_elec_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert LepIDstat_elec_2018-Trigger_2016preVFP-Trigger_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Trigger_2017-Trigger_2018-PU
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Prefire-JER_2016preVFP-JER_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JER_2017-JER_2018-Unclustered_2016preVFP
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert Unclustered_2016-Unclustered_2017-Unclustered_2018
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_AbsoluteMPFBias-JES_AbsoluteScale-JES_AbsoluteStat_2016preVFP
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_AbsoluteStat_2016-JES_AbsoluteStat_2017-JES_AbsoluteStat_2018
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeBal-JES_RelativeFSR-JES_RelativeJEREC1_2016preVFP
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeJEREC1_2016-JES_RelativeJEREC1_2017-JES_RelativeJEREC1_2018
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeJEREC2_2016preVFP-JES_RelativeJEREC2_2016-JES_RelativeJEREC2_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeJEREC2_2018-JES_RelativeJERHF-JES_RelativePtBB
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativePtEC1_2016preVFP-JES_RelativePtEC1_2016-JES_RelativePtEC1_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativePtEC1_2018-JES_RelativePtEC2_2016preVFP-JES_RelativePtEC2_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativePtEC2_2017-JES_RelativePtEC2_2018-JES_RelativePtHF
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeStatEC_2016preVFP-JES_RelativeStatEC_2016-JES_RelativeStatEC_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeStatEC_2018-JES_RelativeStatFSR_2016preVFP-JES_RelativeStatFSR_2016
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeStatFSR_2017-JES_RelativeStatFSR_2018-JES_RelativeStatHF_2016preVFP
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeStatHF_2016-JES_RelativeStatHF_2017-JES_RelativeStatHF_2018
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeSample_2016preVFP-JES_RelativeSample_2016-JES_RelativeSample_2017
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_RelativeSample_2018-JES_PileUpDataMC-JES_PileUpPtBB
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_PileUpPtEC1-JES_PileUpPtEC2-JES_PileUpPtHF
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_PileUpPtRef-JES_FlavorQCD-JES_Fragmentation
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_SinglePionECAL-JES_SinglePionHCAL-JES_TimePtEta_2016preVFP
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert JES_TimePtEta_2016-JES_TimePtEta_2017-JES_TimePtEta_2018
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_1-PDF_2-PDF_3
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_4-PDF_5-PDF_6
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_7-PDF_8-PDF_9
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_10-PDF_11-PDF_12
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_13-PDF_14-PDF_15
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_16-PDF_17-PDF_18
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_19-PDF_20-PDF_21
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_22-PDF_23-PDF_24
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_25-PDF_26-PDF_27
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_28-PDF_29-PDF_30
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_31-PDF_32-PDF_33
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_34-PDF_35-PDF_36
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_37-PDF_38-PDF_39
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_40-PDF_41-PDF_42
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_43-PDF_44-PDF_45
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_46-PDF_47-PDF_48
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_49-PDF_50-PDF_51
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_52-PDF_53-PDF_54
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_55-PDF_56-PDF_57
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_58-PDF_59-PDF_60
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_61-PDF_62-PDF_63
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_64-PDF_65-PDF_66
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_67-PDF_68-PDF_69
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_70-PDF_71-PDF_72
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_73-PDF_74-PDF_75
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_76-PDF_77-PDF_78
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_79-PDF_80-PDF_81
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_82-PDF_83-PDF_84
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_85-PDF_86-PDF_87
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_88-PDF_89-PDF_90
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_91-PDF_92-PDF_93
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_94-PDF_95-PDF_96
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_97-PDF_98
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert PDF_99-PDF_100
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch1_bin0-prop_binch1_bin1
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch1_bin2-prop_binch1_bin3
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch1_bin4-prop_binch2_bin0
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin1-prop_binch2_bin10
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin11-prop_binch2_bin12
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin13-prop_binch2_bin2
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin3-prop_binch2_bin4
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin5-prop_binch2_bin6
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin7-prop_binch2_bin8
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch2_bin9-prop_binch3_bin0
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch3_bin1-prop_binch3_bin2
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch3_bin3-prop_binch3_bin4
python runCombine_threePoint.py --year=ULRunII --light --minus --binning=A --SMZero --region=combined --impacts --noScan --noDefaultFit --fullFit --uncert prop_binch3_bin5-prop_binch3_bin6
