python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_20to30 --nJobs=36 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_20to30 --nJobs=36 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_30to50 --nJobs=32 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_30to50 --nJobs=32 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_30to50 --nJobs=32 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=38
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=39
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=37
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=38
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=39
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=41
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=43
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=45
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=48
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=49
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=51
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=38
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=39
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=41
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=43
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=44
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=45
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=46
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 --nJobs=13 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 --nJobs=13 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 --nJobs=13 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 --nJobs=13 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 --nJobs=13 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 --nJobs=13 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_80to170 --nJobs=17 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_80to170 --nJobs=17 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_80to170 --nJobs=17 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=99
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=101
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=102
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=103
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=104
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=105
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=106
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=107
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=108
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=109
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=110
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=111
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=112
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=113
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=114
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=115
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=116
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=117
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=118
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=119
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=120
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=121
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=122
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=123
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=124
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=125
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=126
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=127
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=128
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=129
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=130
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=131
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=132
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=133
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=134
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=135
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=136
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=137
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=138
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=139
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=140
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=141
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=142
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=143
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=144
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=145
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=146
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=147
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=148
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=149
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=150
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=151
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=152
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=153
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=154
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=0
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2017B --nJobs=30 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=0
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=9
