python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_30to50 --nJobs=32 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 --nJobs=19 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 --nJobs=30 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 --nJobs=33 --job=32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 --nJobs=33 --job=30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 --nJobs=36 --job=30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=39
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 --nJobs=42 --job=40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=41
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=44
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 --nJobs=52 --job=51
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=38
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=42
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=43
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 --nJobs=47 --job=45
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf --nJobs=17 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=0
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 --nJobs=23 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 --nJobs=27 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 --nJobs=27 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 --nJobs=27 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 --nJobs=27 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 --nJobs=27 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 --nJobs=27 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=37
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=38
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=39
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO --nJobs=42 --job=41
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=37
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=38
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=39
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=41
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=42
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=43
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=44
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=45
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=46
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=47
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=48
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=49
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=50
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=51
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=52
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=53
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=54
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=55
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=56
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=57
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=58
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=59
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=60
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=61
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=62
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=63
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=64
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=65
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=66
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=67
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=68
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=69
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=70
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=71
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=72
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=73
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=74
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=75
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=76
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=77
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=78
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=79
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=80
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=81
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=82
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=83
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=84
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=85
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=86
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=87
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=88
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=89
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=90
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=91
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=92
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=93
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=94
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=95
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=96
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=97
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=98
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=99
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=101
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=102
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=103
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=104
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=105
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=106
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=107
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=108
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=109
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=110
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=111
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=112
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=113
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=114
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=115
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=116
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=117
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=118
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=119
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=120
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=121
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=122
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=123
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=124
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=125
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=126
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=127
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=128
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=129
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=130
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=131
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=132
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=133
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=134
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=135
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=136
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=137
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=138
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=139
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=140
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=141
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=142
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=143
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=144
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=145
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=146
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=147
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=148
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=149
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=150
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=151
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=152
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=153
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 --nJobs=155 --job=154
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=117
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=118
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=119
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=120
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=121
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=122
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=123
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=124
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=125
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=126
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=127
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=128
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=129
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=130
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=131
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=132
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=133
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=134
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=135
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=136
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=137
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=138
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=139
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=140
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=141
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=142
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=143
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=144
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=145
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=146
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=147
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=148
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=149
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=150
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=151
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=152
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=153
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=154
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=155
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=156
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=157
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=158
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=159
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=160
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=161
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=162
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=163
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=164
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=165
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=166
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=167
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=168
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=169
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=170
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=171
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=172
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=173
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=174
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=175
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=176
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=177
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=178
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=179
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=180
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=181
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=182
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=183
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=184
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=185
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=186
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=187
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=188
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=189
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=190
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=191
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=192
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=193
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=194
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=195
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=196
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=197
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=198
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 --nJobs=200 --job=199
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample ZZ --nJobs=10 --job=9
