python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=0
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2017 --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2017B --nJobs=10 --job=9
