python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample ZZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTZ_EFT #SPLIT200

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample DYJetsToLL_M10to50_LO  #SPLIT34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample DYJetsToLL_M50 #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTLep_pow_CP5 #SPLIT49
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTSingleLep_pow_CP5 #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTHad_pow_CP5 #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTHTobb #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTHnobb #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTWToLNu #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTWToQQ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTZToQQ #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTZToLLNuNu #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTZToLLNuNu_m1to10 #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample T_tch_pow #SPLIT86
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TBar_tch_pow #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample T_tWch #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TBar_tWch #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tZq_ll #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_thad_Wlept_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_thad_Wlept_DS
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Whad_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Whad_DS #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Wlept_DR #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Wlept_DS #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WW #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample ZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WWW_4F #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WWZ_4F #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WZZ #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample ZZZ #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WZTo3LNu #SPLIT31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTTT #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTWW #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTWZ #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTZZ #SPLIT4
