python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_15to20 #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_20to30 #SPLIT36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_30to50 #SPLIT32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 #SPLIT19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 #SPLIT36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 #SPLIT42
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 #SPLIT52
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 #SPLIT47
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf #SPLIT17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_15to20 #SPLIT18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_20to30 #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 #SPLIT13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_50to80 #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_80to120 #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_120to170 #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_170to300 #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_300toInf #SPLIT3
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 #SPLIT23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 #SPLIT27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_30to80 #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_80to170 #SPLIT17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_170to250 #SPLIT14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_250toInf #SPLIT22

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO  #SPLIT42
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M50 #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 #SPLIT155
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample WJetsToLNu  #SPLIT47
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample WW #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample WZ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample ZZ #SPLIT10

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016Bver1_preVFP #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016Bver2_preVFP #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016C_preVFP #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016D_preVFP #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016E_preVFP #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016F_preVFP #SPLIT10

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016Bver1_preVFP #SPLIT1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016Bver2_preVFP #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016C_preVFP #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016D_preVFP #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016E_preVFP #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016F_preVFP #SPLIT10
