python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_15to20 #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_20to30 #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_30to50 #SPLIT13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_50to80 #SPLIT17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_80to120 #SPLIT22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_120to170 #SPLIT16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_170to300 #SPLIT36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_300to470 #SPLIT16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_470to600 #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_600to800 #SPLIT29
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_800to1000 #SPLIT42
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_MuEnriched_1000toInf #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_15to20 #SPLIT27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_20to30 #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_30to50 #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_50to80 #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_80to120 #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_120to170 #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_170to300 #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_EMEnriched_300toInf #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_bcToE_15to20 #SPLIT41
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_bcToE_20to30 #SPLIT14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_bcToE_30to80 #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_bcToE_80to170 #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_bcToE_170to250 #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample QCD_bcToE_250toInf #SPLIT11

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample DYJetsToLL_M10to50_LO  #SPLIT17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample DYJetsToLL_M50 #SPLIT32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTLep_pow_CP5 #SPLIT25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample TTSingleLep_pow_CP5 #SPLIT70
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WJetsToLNu  #SPLIT34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WW #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample WZ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample ZZ #SPLIT9

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample SingleMuon_Run2016F #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample SingleMuon_Run2016G #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample SingleMuon_Run2016H #SPLIT41

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample SingleElectron_Run2016F #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample SingleElectron_Run2016G #SPLIT36
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016 --processingEra tWZ_UL_nAODv9_v3 --sample SingleElectron_Run2016H #SPLIT40
