python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ZZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTZ_EFT #SPLIT200

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WZTo3LNu_powheg #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample DYJetsToLL_M10to50_LO  #SPLIT34
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample DYJetsToLL_M50 #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTLep_pow_CP5 #SPLIT49
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTSingleLep_pow_CP5 #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTHad_pow_CP5 #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTHTobb #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTHnobb #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTWToLNu #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTWToQQ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTZToQQ #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTZToLLNuNu #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTZToLLNuNu_m1to10 #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample T_tch_pow #SPLIT86
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TBar_tch_pow #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample T_tWch #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TBar_tWch #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tZq_ll #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tWll_thad_Wlept_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tWll_thad_Wlept_DS
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Whad_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Whad_DS #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Wlept_DR #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Wlept_DS #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WW #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WWW_4F #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WWZ_4F #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WZZ #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ZZZ #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample WZTo3LNu #SPLIT31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTTT #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTWW #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTWZ #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTZZ #SPLIT4

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTGammaDilep #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTGammaHadronic #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTGammaSinglelep #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample Zgamma #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2e2mu #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2e2nu #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2e2tau #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2mu2nu #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2mu2tau #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_4e #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_4mu
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_4tau #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample VHToNonbb #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample VBF_HToZZTo4L #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToHToZZTo2L2Q #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ggToHToZZTo4L #SPLIT4

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample TTW_EWK #SPLIT30
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016 --processingEra tWZ_UL_nAODv9_v5 --sample ZZ_powheg #SPLIT49
