python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ZZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTZ_EFT #SPLIT200

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WZTo3LNu_powheg #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample DYJetsToLL_M10to50_LO  #SPLIT19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample DYJetsToLL_M50 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTLep_pow_CP5 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTSingleLep_pow_CP5 #SPLIT60
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTHad_pow_CP5 #SPLIT40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTHTobb #SPLIT25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTHnobb #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTWToLNu #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTWToQQ #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTZToQQ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTZToLLNuNu #SPLIT15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTZToLLNuNu_m1to10 #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample T_tch_pow #SPLIT49
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TBar_tch_pow #SPLIT46
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample T_tWch #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TBar_tWch #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tZq_ll #SPLIT13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tWll_thad_Wlept_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tWll_thad_Wlept_DS #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Whad_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Whad_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Wlept_DR #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample tWll_tlept_Wlept_DS #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WW #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WZ #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ZZ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WWW_4F #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WWZ_4F #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WZZ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ZZZ #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample WZTo3LNu #SPLIT32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTTT #SPLIT18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTWW #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTWZ
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTZZ #SPLIT4

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTGammaDilep #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTGammaHadronic #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTGammaSinglelep #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample Zgamma #SPLIT12
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2e2mu #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2e2nu #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2e2tau #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2mu2nu #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_2mu2tau #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_4e #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_4mu #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToZZ_4tau #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample VHToNonbb #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample VBF_HToZZTo4L #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToHToZZTo2L2Q
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ggToHToZZTo4L #SPLIT2

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample TTW_EWK #SPLIT22
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v5 --sample ZZ_powheg #SPLIT22
