python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample ZZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTZ_EFT #SPLIT200

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample DYJetsToLL_M10to50_LO  #SPLIT19
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample DYJetsToLL_M50 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTLep_pow_CP5 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTSingleLep_pow_CP5 #SPLIT60
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTHad_pow_CP5 #SPLIT40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTHTobb #SPLIT25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTHnobb #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTWToLNu #SPLIT26
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTWToQQ #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTZToQQ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTZToLLNuNu #SPLIT15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTZToLLNuNu_m1to10 #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample T_tch_pow #SPLIT49
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TBar_tch_pow #SPLIT46
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample T_tWch #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TBar_tWch #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tZq_ll #SPLIT13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tWll_thad_Wlept_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tWll_thad_Wlept_DS #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Whad_DR #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Whad_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Wlept_DR #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Wlept_DS #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WW #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WZ #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample ZZ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WWW_4F #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WWZ_4F #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WZZ #SPLIT8
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample ZZZ #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample WZTo3LNu #SPLIT32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTTT #SPLIT18
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTWW #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTWZ
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v4 --sample TTZZ #SPLIT4
