python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample ZZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WZ_EFT #SPLIT200
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTZ_EFT #SPLIT200

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample DYJetsToLL_M10to50_LO  #SPLIT42
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample DYJetsToLL_M50 #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTLep_pow_CP5 #SPLIT155
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTSingleLep_pow_CP5 #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTHad_pow_CP5 #SPLIT100
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTHTobb #SPLIT57
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTHnobb #SPLIT48
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTWToLNu #SPLIT13
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTWToQQ #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTZToQQ #SPLIT23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTZToLLNuNu #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTZToLLNuNu_m1to10 #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample T_tch_pow #SPLIT149
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TBar_tch_pow #SPLIT130
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample T_tWch #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TBar_tWch #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tZq_ll #SPLIT14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_thad_Wlept_DR #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_thad_Wlept_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Whad_DR #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Whad_DS #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Wlept_DR #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample tWll_tlept_Wlept_DS
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WW #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WZTo3LNu #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample ZZ #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WWW_4F #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WWZ_4F #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample WZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample ZZZ #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTTT #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTWW #SPLIT3
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTWZ
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2018 --processingEra tWZ_UL_nAODv9_v3 --sample TTZZ #SPLIT4
