# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ZZ_EFT #SPLIT200
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WZ_EFT #SPLIT200
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTZ_EFT #SPLIT200

# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WZTo3LNu_powheg #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample DYJetsToLL_M10to50_LO  #SPLIT42
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample DYJetsToLL_M50 #SPLIT35
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTLep_pow_CP5 #SPLIT99
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTSingleLep_pow_CP5 #SPLIT150
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTHad_pow_CP5 #SPLIT100
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTHTobb #SPLIT46
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTHnobb #SPLIT35
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTWToLNu #SPLIT9
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTWToQQ #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTZToQQ #SPLIT20
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTZToLLNuNu #SPLIT19
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTZToLLNuNu_m1to10 #SPLIT7
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample T_tch_pow #SPLIT100
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TBar_tch_pow #SPLIT60
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample T_tWch #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TBar_tWch #SPLIT5
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tZq_ll #SPLIT12
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tWll_thad_Wlept_DR #SPLIT3
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tWll_thad_Wlept_DS #SPLIT2
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Whad_DR #SPLIT2
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Whad_DS #SPLIT2
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Wlept_DR #SPLIT5
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample tWll_tlept_Wlept_DS #SPLIT6
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WW #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WZ #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ZZ #SPLIT2
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WWW_4F #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WWZ_4F #SPLIT5
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WZZ #SPLIT2
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ZZZ #SPLIT8
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample WZTo3LNu #SPLIT31
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTTT #SPLIT20
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTWW #SPLIT5
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTWZ
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTZZ #SPLIT5

# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTGammaDilep #SPLIT6
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTGammaHadronic #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTGammaSinglelep #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample Zgamma #SPLIT22
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_2e2mu #SPLIT11
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_2e2nu #SPLIT6
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_2e2tau #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_2mu2nu #SPLIT6
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_2mu2tau #SPLIT10
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_4e #SPLIT13
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_4mu #SPLIT15
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToZZ_4tau #SPLIT9
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample VHToNonbb #SPLIT6
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample VBF_HToZZTo4L #SPLIT7
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToHToZZTo2L2Q #SPLIT8
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ggToHToZZTo4L #SPLIT7

# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample TTW_EWK #SPLIT27
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim trilep --year UL2017 --processingEra tWZ_UL_nAODv9_v4 --sample ZZ_powheg #SPLIT54
