python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_15to20 #SPLIT14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_20to30 #SPLIT25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_30to50 #SPLIT24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_50to80 #SPLIT15
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_80to120 #SPLIT28
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_120to170 #SPLIT16
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_170to300 #SPLIT32
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_300to470 #SPLIT23
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_470to600 #SPLIT24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_600to800 #SPLIT31
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_800to1000 #SPLIT40
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_MuEnriched_1000toInf #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_15to20 #SPLIT21
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_20to30 #SPLIT5
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_30to50 #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_50to80 #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_80to120 #SPLIT6
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_120to170 #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_170to300 #SPLIT4
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_EMEnriched_300toInf #SPLIT7
# python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_15to20 #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_20to30 #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_30to80 #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_80to170 #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_170to250 #SPLIT9
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample QCD_bcToE_250toInf #SPLIT13

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M10to50_LO  #SPLIT10
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample DYJetsToLL_M50 #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTLep_pow_CP5 #SPLIT17
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample TTSingleLep_pow_CP5 #SPLIT59
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample WJetsToLNu  #SPLIT102
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample WW #SPLIT11
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample WZ #SPLIT7
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample ZZ #SPLIT4

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016Bver1_preVFP #SPLIT2
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016Bver2_preVFP #SPLIT35
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016C_preVFP #SPLIT14
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016D_preVFP #SPLIT20
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016E_preVFP #SPLIT24
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleMuon_Run2016F_preVFP #SPLIT22

python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016Bver1_preVFP #SPLIT1
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016Bver2_preVFP #SPLIT53
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016C_preVFP #SPLIT25
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016D_preVFP #SPLIT33
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016E_preVFP #SPLIT37
python nanoPostProcessing_UL.py  --overwrite --forceProxy --skim singlelep --triggerSelection --year UL2016_preVFP --processingEra tWZ_UL_nAODv9_v1 --sample SingleElectron_Run2016F_preVFP #SPLIT20
