python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_b_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_b_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_l_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_l_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Trigger_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Trigger_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Prescale_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Prescale_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=PU_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=PU_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JES_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JES_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JER_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JER_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDstat_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDstat_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDsys_UP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDsys_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_UPUP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_UPNONE
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_NONEUP
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_DOWNDOWN
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_DOWNNONE
python EFT_UL.py --selection=trilepT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_NONEDOWN 

python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_b_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_b_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_l_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_l_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Trigger_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Trigger_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Prescale_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Prescale_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=PU_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=PU_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=JES_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=JES_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=JER_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=JER_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDstat_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDstat_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDsys_UP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDsys_DOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_UPUP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_UPNONE
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_NONEUP
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_DOWNDOWN
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_DOWNNONE
python EFT_UL.py --selection=trilepT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_NONEDOWN 

python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_b_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_b_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_l_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=BTag_l_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Trigger_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Trigger_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Prescale_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Prescale_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=PU_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=PU_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JES_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JES_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JER_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=JER_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDstat_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDstat_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDsys_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=LepIDsys_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_UPUP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_UPNONE
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_NONEUP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_DOWNDOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_DOWNNONE
python EFT_UL.py --selection=trilepFOnoT-minDLmass12-onZ1 --nicePlots --era=ULRunII --sys=Scale_NONEDOWN 

python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_b_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_b_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_l_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=BTag_l_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Trigger_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Trigger_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Prescale_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Prescale_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=PU_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=PU_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=JES_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=JES_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=JER_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=JER_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDstat_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDstat_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDsys_UP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=LepIDsys_DOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_UPUP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_UPNONE
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_NONEUP
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_DOWNDOWN
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_DOWNNONE
python EFT_UL.py --selection=trilepFOnoT-minDLmass12 --nicePlots --era=ULRunII --sys=Scale_NONEDOWN 
