################################################################################
# TTZ 3 jets
python EFT_UL.py --reduceEFT --noData --nicePlots --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=WZnJet
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_correlated_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_correlated_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_correlated_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_correlated_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016preVFP_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016preVFP_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016preVFP_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016preVFP_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_correlated_161718_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_correlated_161718_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_correlated_1718_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Lumi_correlated_1718_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Trigger_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Trigger_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Prefire_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Prefire_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepReco_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepReco_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2016preVFP_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2016preVFP_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDstat_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDsys_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=LepIDsys_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PU_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PU_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=JES_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=JES_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=JER_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=JER_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=ISR_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=ISR_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=FSR_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=FSR_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Scale_UPNONE
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Scale_DOWNNONE
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Scale_NONEUP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=Scale_NONEDOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_1
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_2
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_3
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_4
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_5
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_6
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_7
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_8
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_9
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_10
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_11
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_12
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_13
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_14
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_15
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_16
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_17
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_18
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_19
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_20
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_21
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_22
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_23
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_24
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_25
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_26
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_27
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_28
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_29
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_30
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_31
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_32
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_33
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_34
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_35
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_36
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_37
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_38
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_39
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_40
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_41
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_42
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_43
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_44
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_45
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_46
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_47
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_48
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_49
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_50
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_51
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_52
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_53
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_54
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_55
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_56
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_57
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_58
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_59
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_60
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_61
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_62
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_63
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_64
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_65
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_66
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_67
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_68
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_69
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_70
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_71
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_72
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_73
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_74
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_75
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_76
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_77
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_78
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_79
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_80
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_81
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_82
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_83
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_84
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_85
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_86
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_87
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_88
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_89
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_90
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_91
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_92
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_93
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_94
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_95
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_96
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_97
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_98
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_99
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --sys=PDF_100

################################################################################
# TTZ 4+ jets
python EFT_UL.py --reduceEFT --noData --nicePlots --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=WZnJet
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_correlated_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_correlated_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_correlated_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_correlated_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016preVFP_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016preVFP_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016preVFP_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016preVFP_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_b_uncorrelated_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=BTag_l_uncorrelated_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_uncorrelated_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_correlated_161718_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_correlated_161718_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_correlated_1718_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Lumi_correlated_1718_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Trigger_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Trigger_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Prefire_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Prefire_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepReco_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepReco_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2016preVFP_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2016preVFP_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2016_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2016_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2017_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2017_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2018_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDstat_2018_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDsys_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=LepIDsys_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PU_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PU_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=JES_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=JES_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=JER_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=JER_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=ISR_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=ISR_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=FSR_UP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=FSR_DOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Scale_UPNONE
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Scale_DOWNNONE
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Scale_NONEUP
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=Scale_NONEDOWN
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_1
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_2
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_3
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_4
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_5
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_6
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_7
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_8
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_9
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_10
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_11
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_12
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_13
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_14
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_15
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_16
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_17
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_18
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_19
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_20
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_21
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_22
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_23
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_24
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_25
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_26
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_27
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_28
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_29
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_30
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_31
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_32
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_33
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_34
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_35
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_36
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_37
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_38
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_39
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_40
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_41
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_42
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_43
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_44
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_45
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_46
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_47
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_48
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_49
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_50
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_51
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_52
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_53
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_54
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_55
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_56
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_57
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_58
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_59
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_60
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_61
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_62
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_63
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_64
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_65
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_66
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_67
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_68
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_69
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_70
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_71
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_72
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_73
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_74
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_75
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_76
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_77
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_78
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_79
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_80
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_81
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_82
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_83
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_84
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_85
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_86
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_87
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_88
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_89
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_90
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_91
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_92
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_93
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_94
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_95
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_96
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_97
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_98
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_99
python EFT_UL.py --reduceEFT --noData --threePoint --selection=trilepT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --sys=PDF_100

################################################################################
# TTZ CR 3 jets
python EFT_UL.py --nicePlots --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=Fakerate_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=Fakerate_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_elec_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_elec_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016preVFP_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016preVFP_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2017_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2017_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2018_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2018_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_muon_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_muon_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016preVFP_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016preVFP_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2017_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2017_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2018_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2018_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_both_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_both_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016preVFP_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016preVFP_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2017_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2017_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2018_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet3-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2018_DOWN

################################################################################
# TTZ CR 4+ jets
python EFT_UL.py --nicePlots --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=Fakerate_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=Fakerate_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_elec_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_elec_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016preVFP_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016preVFP_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2016_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2017_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2017_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2018_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_elec_2018_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_muon_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_muon_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016preVFP_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016preVFP_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2016_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2017_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2017_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2018_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_muon_2018_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_both_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_correlated_both_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016preVFP_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016preVFP_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2016_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2017_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2017_DOWN
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2018_UP
python EFT_UL.py --threePoint --selection=trilepFOnoT-minDLmass12-onZ1-njet4p-btag1p --era=UL2017 --applyFakerate --useDataSF --sys=FakerateClosure_uncorrelated_both_2018_DOWN
